import { cp, mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const outputDirectory = resolve(projectRoot, 'dist');
const stagingDirectory = resolve(projectRoot, `.dist-stage-${process.pid}`);
const require = createRequire(import.meta.url);
// One token source for extension pages and the injected Shadow DOM.
const { tokensCSS } = require(join(projectRoot, 'src/ui/design-system.js'));
await writeFile(join(projectRoot, 'src/ui/design-tokens.css'), `/* Generated by scripts/build.mjs from design-system.js. */\n${tokensCSS}\n`);

if (dirname(outputDirectory) !== projectRoot || dirname(stagingDirectory) !== projectRoot) {
  throw new Error('构建目录必须位于项目根目录内');
}

const requiredPaths = [
  'manifest.json',
  'background.js',
  'content.js',
  'options.html',
  'options.js',
  'popup.html',
  'popup.js',
  'src/ui/design-system.js',
  'src/ui/design-tokens.css',
  'src/ui/profile-coverage.js',
  'src/ui/review-presenter.js',
  'src/ui/popup.css',
  'src/ui/options.css',
  'src/ui/options-workspace.js',
  'LICENSE',
  'icons',
  'src/adapters/generic.js',
  'src/adapters/site-profile.js',
  'src/adapters/registry.js',
  'src/adapters/generic-adapter.js',
  'src/adapters/undergraduate-awards.js',
  'src/content-app.js',
  'src/content-controller.js',
  'src/semantics/boolean-semantic-adapter.js',
  'src/semantics/field-semantic-normalizer.js',
  'src/controls/control-adapter-registry.js',
  'src/controls/adapters/native-value-adapter.js',
  'src/controls/adapters/native-select-adapter.js',
  'src/controls/adapters/choice-adapter.js',
  'src/controls/adapters/cascader-adapter.js',
  'src/controls/adapters/custom-select-adapter.js',
  'src/controls/adapters/date-like-adapter.js',
  'src/controls/adapters/compound-picker-adapter.js',
  'src/core/array-handler.js',
  'src/core/autofill-engine.js',
  'src/core/current-section-resolver.js',
  'src/core/diagnostic-sanitizer.js',
  'src/core/embedded-section-detector.js',
  'src/core/event-dispatcher.js',
  'src/core/field-context.js',
  'src/core/field-detector.js',
  'src/core/field-matcher.js',
  'src/core/file-field-detector.js',
  'src/core/file-matcher.js',
  'src/core/file-upload-engine.js',
  'src/core/form-filler.js',
  'src/core/navigation-engine.js',
  'src/core/page-ready.js',
  'src/core/report-manager.js',
  'src/core/safety.js',
  'src/core/save-handler.js',
  'src/core/semantic-verification.js',
  'src/core/task-state.js',
  'src/core/verification-engine.js',
  'src/floating-ui/drag-controller.js',
  'src/floating-ui/floating-panel.js',
  'src/floating-ui/panel-state.js',
  'src/floating-ui/resize-controller.js',
  'src/mappings/date-rules.js',
  'src/mappings/field-aliases.js',
  'src/mappings/file-field-aliases.js',
  'src/mappings/option-aliases.js',
  'src/mappings/section-aliases.js',
  'src/mappings/section-structures.js',
  'src/storage/indexeddb.js',
  'src/storage/material-library-ui.js',
  'src/storage/material-library.js',
  'src/storage/resume-store.js',
  'config/site-adapters.json',
];

const optionalPaths = [
  'README.md',
  'resume-data.example.json',
  'src',
  'samples',
  'config',
  'docs',
];

await rm(stagingDirectory, { recursive: true, force: true });
await mkdir(stagingDirectory, { recursive: true });

try {
  for (const relativePath of requiredPaths) {
    const source = join(projectRoot, relativePath);
    await assertExists(source, relativePath);
    await copy(source, join(stagingDirectory, relativePath));
  }

  for (const relativePath of optionalPaths) {
    const source = join(projectRoot, relativePath);
    if (await exists(source)) {
      await copy(source, join(stagingDirectory, relativePath));
    }
  }

  const manifestText = await readFile(join(stagingDirectory, 'manifest.json'), 'utf8');
  const manifest = JSON.parse(manifestText);
  if (manifest.manifest_version !== 3) {
    throw new Error('仅支持构建 Manifest V3 扩展');
  }
  await assertManifestResourcesExist(manifest, stagingDirectory);

  await rm(outputDirectory, { recursive: true, force: true });
  await rename(stagingDirectory, outputDirectory);
  console.log(`构建完成：${outputDirectory}`);
} catch (error) {
  await rm(stagingDirectory, { recursive: true, force: true });
  throw error;
}

async function copy(source, destination) {
  await mkdir(dirname(destination), { recursive: true });
  await cp(source, destination, { recursive: true, force: true });
}

async function exists(path) {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (error?.code === 'ENOENT') return false;
    throw error;
  }
}

async function assertExists(path, label) {
  if (!await exists(path)) {
    throw new Error(`缺少扩展必需文件：${label}`);
  }
}

async function assertManifestResourcesExist(manifest, directory) {
  const paths = new Set([
    manifest.background?.service_worker,
    manifest.action?.default_popup,
    manifest.options_page,
    ...Object.values(manifest.icons || {}),
    ...Object.values(manifest.action?.default_icon || {}),
    ...(manifest.content_scripts || []).flatMap(entry => [...(entry.js || []), ...(entry.css || [])]),
  ].filter(Boolean));

  for (const relativePath of paths) {
    if (/[*?{}]/.test(relativePath)) continue;
    await assertExists(join(directory, relativePath), `manifest 引用资源 ${relativePath}`);
  }
}
